version: '3'
services:
  coretrix:
    restart: always
    ports: 
      - "8080:8080"
    environment:
      - LIVE=true
    build: .
  mongo:
    image: mongo:3.2
    restart: always
    ports: 
      - "27017:27017"
    environment:
      MONGO_INITDB_ROOT_USERNAME: themadprogrammer
      MONGO_INITDB_ROOT_PASSWORD: loVeA6irl
